apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
        - name: user-microservice
          image: ishaaa1/user-microservice:v1.0
          ports:
            - containerPort: 3000
