apiVersion: v1
kind: Service
metadata:
  name: user-microservice-service
spec:
  selector:
    app: user-microservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer # Use NodePort if on Minikube
